version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/src/assets/data"
    schedule:
      interval: "daily"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
