/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtons: typeof import('./src/components/card/ActionButtons.vue')['default']
    AppBarComponent: typeof import('./src/components/AppBarComponent.vue')['default']
    Card: typeof import('./src/components/card/index.vue')['default']
    CardDialog: typeof import('./src/components/card/CardDialog.vue')['default']
    CardThumbnail: typeof import('./src/components/card/CardThumbnail.vue')['default']
    FilterDialog: typeof import('./src/components/FilterDialog.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    GifDialog: typeof import('./src/components/GifDialog.vue')['default']
    MultiSelect: typeof import('./src/components/MultiSelect.vue')['default']
    ReportDialog: typeof import('./src/components/ReportDialog.vue')['default']
    ResultGrid: typeof import('./src/components/ResultGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
